
# Julia Basics
> adapted from https://github.com/mitmath/julia-mit,
> https://algorithmsbook.com/validation/files/val.pdf#page=397


## Julia as a calculator

In [1]:

3 + 4

7

In [2]:

3 * 4

12

In [3]:

3^4

81

In [4]:

sin(3)

0.1411200080598672

In [5]:

1 / (1 + sin(pi/4))

0.585786437626905


## Variables

In programming languages, a `variable` is a named storage location that holds a value or data.

The variable name appears on the left side of the equal sign; the value that variable
is to be assigned is on the right side.

Variable names can be any string of characters, including Unicode, with a few restrictions.

In [11]:

x = 17

17

In [12]:

y = sin(x)

-0.9613974918795568

In [13]:

α = 3.74 # Unicode variable name — type it by "\alpha<tab>"

3.74

In [14]:

β₂ = sqrt(2) # Unicode variable name — type it by "\beta<tab>\_2<tab>"

1.4142135623730951


#### Strings:

In [15]:

s₁ = "Hello, "

"Hello, "

In [16]:

s₂ = "World!"

"World!"

In [17]:

s₃ = s₁ * s₂

"Hello, World!"

In [18]:

(s₃ * " ")^4

"Hello, World! Hello, World! Hello, World! Hello, World! "


#### Complex number:

In [19]:

z = 3 + 5im

3 + 5im

In [20]:

z^3

-198 + 10im

In [21]:

exp(z)

5.697507299833739 - 19.26050892528742im

In [22]:

sin(z)

10.472508533940392 - 73.46062169567367im


#### Online help:

In [23]:

?sin

search: sin sinc sind sign asin sinh min in stdin sinpi asinh asind using isinf



```julia
sin(x::T) where {T <: Number} -> float(T)
```

Compute sine of `x`, where `x` is in radians.

Throw a [`DomainError`](@ref) if `isinf(x)`, return a `T(NaN)` if `isnan(x)`.

See also [`sind`](@ref), [`sinpi`](@ref), [`sincos`](@ref), [`cis`](@ref), [`asin`](@ref).

# Examples

```jldoctest
julia> round.(sin.(range(0, 2pi, length=9)'), digits=3)
1×9 Matrix{Float64}:
 0.0  0.707  1.0  0.707  0.0  -0.707  -1.0  -0.707  -0.0

julia> sind(45)
0.7071067811865476

julia> sinpi(1/4)
0.7071067811865475

julia> round.(sincos(pi/6), digits=3)
(0.5, 0.866)

julia> round(cis(pi/6), digits=3)
0.866 + 0.5im

julia> round(exp(im*pi/6), digits=3)
0.866 + 0.5im
```

---

```julia
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


In [24]:

?β₂

"β₂" can be typed by \beta<tab>\_2<tab>

search: β₂ s₂



No documentation found for private binding `Main.β₂`.

`β₂` is of type `Float64`.

# Summary

```
primitive type Float64
```

# Supertype Hierarchy

```
Float64 <: AbstractFloat <: Real <: Number <: Any
```


In [25]:

?exp

search: exp exp2 expm1 frexp exp10 ldexp export Expr help Text exit



```julia
exp(x)
```

Compute the natural base exponential of `x`, in other words $ℯ^x$.

See also [`exp2`](@ref), [`exp10`](@ref) and [`cis`](@ref).

# Examples

```jldoctest
julia> exp(1.0)
2.718281828459045

julia> exp(im * pi) ≈ cis(pi)
true
```

---

```julia
exp(A::AbstractMatrix)
```

Compute the matrix exponential of `A`, defined by

$$
e^A = \sum_{n=0}^{\infty} \frac{A^n}{n!}.
$$

For symmetric or Hermitian `A`, an eigendecomposition ([`eigen`](@ref)) is used, otherwise the scaling and squaring algorithm (see [^H05]) is chosen.

[^H05]: Nicholas J. Higham, "The squaring and scaling method for the matrix exponential revisited", SIAM Journal on Matrix Analysis and Applications, 26(4), 2005, 1179-1193. [doi:10.1137/090768539](https://doi.org/10.1137/090768539)

# Examples

```jldoctest
julia> A = Matrix(1.0I, 2, 2)
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

julia> exp(A)
2×2 Matrix{Float64}:
 2.71828  0.0
 0.0      2.71828
```



#### Printing

Only the "result" of the last line in a cell is displayed: 

In [26]:

z
x
s₁

"Hello, "


Different ways to display everything:

In [27]:

println(x)
@show  s₁
@info y

17
s₁ = "Hello, "


[ Info: -0.9613974918795568



## Vectors

A vector is a one-dimensional array that stores a sequence of values. We can
construct a vector using **square brackets**, separating elements by commas or spaces:

In [28]:

x = [1, 17, 32, 15]  # column vector; elements separated by commas

4-element Vector{Int64}:
  1
 17
 32
 15

In [29]:

[0 1 2] # row "vector"; elements separated by spaces

1×3 Matrix{Int64}:
 0  1  2

In [30]:
y = [15, 2, 6, -9]

4-element Vector{Int64}:
 15
  2
  6
 -9

In [31]:
x + y

4-element Vector{Int64}:
 16
 19
 38
  6

In [32]:

x * y # not allowed: vector * vector is not a linear-algebra operation

LoadError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:642
  *(::LinearAlgebra.Transpose{T, <:AbstractVector}, ::AbstractVector{T}) where T<:Real
   @ LinearAlgebra ~/.julia/juliaup/julia-1.12.6+0.x64.linux.gnu/share/julia/stdlib/v1.12/LinearAlgebra/src/adjtrans.jl:502
  *(::LinearAlgebra.UniformScaling, ::AbstractVecOrMat)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.12.6+0.x64.linux.gnu/share/julia/stdlib/v1.12/LinearAlgebra/src/uniformscaling.jl:268
  ...


In [33]:

x' # or transpose(x)

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 1  17  32  15

In [34]:

x' * y # allowed = a dot product

106

In [35]:

x .* y # elementwise product

4-element Vector{Int64}:
   15
   34
  192
 -135

In [36]:
float(y)

4-element Vector{Float64}:
 15.0
  2.0
  6.0
 -9.0

In [38]:
float(y) .^ x 

4-element Vector{Float64}:
     15.0
 131072.0
      7.958661109946401e24
     -2.05891132094649e14

In [39]:

z = [3.7, 4.2, 6.1]

3-element Vector{Float64}:
 3.7
 4.2
 6.1

In [40]:

z .^ [0,1,2]

3-element Vector{Float64}:
  1.0
  4.2
 37.209999999999994

In [41]:

z .^ transpose([0,1,2])

3×3 Matrix{Float64}:
 1.0  3.7  13.69
 1.0  4.2  17.64
 1.0  6.1  37.21

In [42]:

z .^ [0 1 2]

3×3 Matrix{Float64}:
 1.0  3.7  13.69
 1.0  4.2  17.64
 1.0  6.1  37.21

In [43]:

@show x
x[2] # second element

x = [1, 17, 32, 15]


17

In [44]:

x[2:3] # elements 2 to 3 — "slicing"

2-element Vector{Int64}:
 17
 32

In [45]:
x[2:4] # elements 2,3,4

3-element Vector{Int64}:
 17
 32
 15

In [46]:

2:4

2:4

In [47]:

typeof(2:4)

UnitRange{Int64}

In [48]:

collect(0:4)

5-element Vector{Int64}:
 0
 1
 2
 3
 4

In [49]:

y .^ 3 # elementwise cube

4-element Vector{Int64}:
 3375
    8
  216
 -729

In [50]:

sin.(y) # elementwise sin

4-element Vector{Float64}:
  0.6502878401571168
  0.9092974268256817
 -0.27941549819892586
 -0.4121184852417566

In [51]:

rand(7) # 7 random numbers in [0,1)

7-element Vector{Float64}:
 0.4797395874368169
 0.7752111967445304
 0.3610649956473573
 0.985223159212717
 0.3589082430808347
 0.11941494721224799
 0.7419917951459247

In [ ]:

randn(7) # 7 normally-distributed random numbers (mean 0, std. dev. 1)

In [ ]:

collect(0:2:7) # 0 to 7 in steps of 2

In [ ]:

collect(0:0.1:7) # 0 to 7 in steps of 0.1

In [ ]:

r = range(0, 2π, 50) # 50 numbers from 0 to 2π, equally spaced

In [ ]:

collect(r)

In [ ]:

r = range(0, 2π, 10^8) # not computed explicitly

In [ ]:

collect(r[1:10])

In [ ]:

x = [] # empty vector

In [ ]:

x = trues(3) # Boolean vector containing three trues

In [ ]:

x = ones(3) # vector of three ones

In [ ]:

x = zeros(3) # vector of three zeros

## Matrices

In [ ]:

A = [1 3 7
     4 7 2
     0 1 1]

In [ ]:

B = [1 3 7; 4 7 2; 0 1 1]

In [ ]:

A == B

In [ ]:

b = [3, 2, 1] # a vector

In [ ]:

A * b # matrix-vector product

In [ ]:

inv(A)


Let's solve a linear system $Ax = b$ for $x$:

In [ ]:

x = inv(A) * b  # Never!

In [ ]:

A * x

In [ ]:

A * x - b # not zero due to roundoff errors


Much better:

In [ ]:

x = A \ b # effectively equivalent to inv(A) * b, but faster and better

In [ ]:

A * x - b # slightly different (smaller in this case)

In [ ]:

sin.(A) # elementwise sine

In [ ]:

sin(A) # what does it mean?

## Functions


### Named functions


One way to define a *named* function is to use the `function` keyword, followed by
the name of the function and a tuple of names of arguments:

In [ ]:

function f(x)
    return 3x^3 - 5x^2 + sin(x) - x
end

In [ ]:

f(3)

In [ ]:

f(A)

In [ ]:

f.(A) # applied elementwise

In [ ]:

f.(x) # applied elementwise


We can also define functions compactly using assignment form:

In [ ]:

g(x) = 4x^3 - 5x^2 + 6x + 2

In [ ]:

g.(A)


### Anonymous functions


An anonymous function is not given a name, though it can be assigned to a named
variable. One way to define an anonymous function is to use the arrow operator:

In [ ]:

h = x -> x^2 + 1 # assign anonymous function with input x to a variable h

In [ ]:

h(3)

In [ ]:

g(f, a, b) = [f(a), f(b)]; # applies function f to a and b and returns array

In [ ]:

g(h, 5, 10)

In [ ]:

g(x->sin(x)+1, 10, 20)


### Optional arguments

We can assign a default value to an argument, making the specification of that
argument optional:

In [ ]:

f(x=10) = x^2;

In [ ]:

f()

In [ ]:
f(3)

In [ ]:

f(x, y, z=1) = x*y + z;

In [ ]:

f(1, 2, 3)

In [ ]:

f(1, 2)


### Keyword arguments

Functions may use keyword arguments, which are arguments that are named
when the function is called. Keyword arguments are given after all the *positional
arguments*. A semicolon is placed before keywords, separating them from
the other arguments:

In [ ]:

f(; x = 0) = x + 1;

In [ ]:

f()

In [ ]:

f(x = 10)

In [ ]:

f(x, y = 10; z = 2) = (x + y) * z;

In [ ]:

f(1)

In [ ]:

f(2, z = 3)

In [ ]:

f(2, 3)

In [ ]:

f(2, 3, z = 1)


### Splatting

It is often useful to splat the elements of a vector or a tuple into the arguments to
a function using the ... operator:

In [ ]:

f(x,y,z) = x + y - z;

In [ ]:

a = [3, 1, 2];
f(a...)

In [ ]:

b = (2, 2, 0);
f(b...)

In [ ]:

c = ([1,2], [3,4], [5,6]);
f(c...)


### Dispatch

The types of the arguments passed to a function can be specified using the double
colon operator. If multiple methods of the same function are provided, Julia will
execute the appropriate method. The mechanism for choosing which method to
execute is called *dispatch*.        

In [ ]:

f(x::Int64) = x + 10;
f(x::Float64) = x + 3.1415;

In [ ]:

f(1)

In [ ]:

f(1.0)


The method with a type signature that best matches the types of the arguments
given will be used:

In [ ]:

f(x) = 5;
f(x::Float64) = 3.1415;

In [ ]:

f([3, 2, 1])

In [ ]:

f(0.00787499699)


## Control Flow

We can control the flow of our programs using *conditional evaluation* and *loops*.


### Conditional Evaluation

Conditional evaluation will check the value of a Boolean expression and then
evaluate the appropriate block of code. One of the most common ways to do this
is with an `if statement`:

In [ ]:

x = 2
y = 1

In [ ]:

if x < y
    2*y   # run this if x < y
elseif x == y
    x + y # run this if x == y
else
    2*x   # run this if x > y
end


We can also use the *ternary operator* with its question mark and colon syntax.
It checks the Boolean expression before the question mark. If the expression
evaluates to true, then it returns what comes before the colon; otherwise, it
returns what comes after the colon:

In [ ]:

g(x) = x > 0 ? x : 0

In [ ]:

g(-10)

In [ ]:

g(10)


### Loops

A loop allows for repeated evaluation of expressions. One type of loop is the
while loop, which repeatedly evaluates a block of expressions until the specified
condition after the while keyword is met. The following example sums the values
in the array X:

In [ ]:

X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
while !isempty(X)
    s += pop!(X)
end

@show s;
@show X;


Another type of loop is the *for* loop, which uses the `for` keyword. The following
example will also sum over the values in the array X but will not modify X:

In [ ]:

X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
for y in X
    s += y
end

@show s;
@show X;


The `in` keyword can be replaced by `=` or `∈`.


## More Linear Algebra

Most linear-algebra routines are in the `LinearAlgebra` standard library:

In [ ]:

using LinearAlgebra 

In [ ]:

eigvals(A) # eigenvalues

In [ ]:

F = eigen(A) # eigenvectors and eigenvalues

In [ ]:

F.values # the eigenvalues

In [ ]:

F.vectors # the eigenvectors

In [ ]:

qr(A) # QR factorization

In [ ]:

lu(A) # LU factorization

In [ ]:

svd(A)


## Plotting

You must load a plotting library. There are lots to choose from. We are using PythonPlot:

In [ ]:

using PythonPlot

In [ ]:

x = rand(5)
plot(x, "bo-")
grid(true);

In [ ]:

x = range(0, 2π, 1000)
y = sin.(3x + 4cos.(2x))
plot(x / 2π, y, label=L"y")
plot(x / 2π, y.^2, label=L"y^2")
plot(x / 2π, 1 ./ sqrt.(1 .+ y.^2), label=L"\frac{1}{\sqrt{1+y^2}}")
xlabel("x / 2π")
ylabel("our funny function")
title("our second plot")
grid(true)
legend();

In [ ]:

?plot


## Markdown

Here is some *italic text*, some **bold text**, some math: 
$$\int_0^1 \frac{1}{1+x^2} \, \mathrm{d}x$$.